AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket for static website hosting.

Parameters:
  EnvironmentName:
    Type: String
    Default: Test
    Description: Environment name for the stack

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'lab-static-site-${EnvironmentName}-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
  WebsiteURL:
    Description: URL for website hosting on S3
    Value: !GetAtt MyS3Bucket.WebsiteURL